import os
import time
import platform

os_atual = platform.system().lower()

if 'windows' in str(os_atual):
    os.system("pip install pyqt5 --user")
    time.sleep(0.5)
    os.system("pip install PySide2 --user")
    time.sleep(0.5)
    os.system("pip install sqlalchemy --user")
    time.sleep(0.5)
    os.system("pip install requests --user")
    time.sleep(0.5)
    os.system("pip install bs4 --user")
    time.sleep(0.5)
    os.system("pip install google_auth_oauthlib --user")
    time.sleep(0.5)
    os.system("pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib --user")
    time.sleep(0.5)
    os.system("pip install urlextract --user")
    time.sleep(0.5)
    os.system("pip install cryptography --user")
    time.sleep(0.5)
    os.system("pip install python-docx --user")
    time.sleep(0.5)
    os.system("pip install fpdf --user")
    time.sleep(0.5)
    os.system("pip install xlwt --user")
    time.sleep(0.5)
    os.system("pip install db-sqlite3 --user")
    time.sleep(0.5)
    os.system("pip install flask --user")
    time.sleep(0.5)
    os.system("pip install flask_restful --user")
    time.sleep(0.5)
    os.system("pip install paramiko --user")
    time.sleep(0.5)
    os.system("pip install boto --user")
    time.sleep(0.5)
    os.system("pip install botocore --user")
    time.sleep(0.5)
    os.system("pip install coloredlogs --user")
    time.sleep(0.5)
    os.system("pip install verboselogs --user")
    time.sleep(0.5)
    os.system("pip install oauth2client==3.0.0 --user")
    time.sleep(0.5)

if 'linux' in str(os_atual):
    os.system("apt install python3-pip")
    time.sleep(0.5)
    os.system("pip3 install pyqt5")
    time.sleep(0.5)
    os.system("pip3 install PySide2")
    time.sleep(0.5)
    os.system("pip3 install sqlalchemy")
    time.sleep(0.5)
    os.system("pip3 install requests")
    time.sleep(0.5)
    os.system("pip3 install bs4")
    time.sleep(0.5)
    os.system("pip3 install google_auth_oauthlib")
    time.sleep(0.5)
    os.system("pip3 install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib")
    time.sleep(0.5)
    os.system("pip3 install urlextract")
    time.sleep(0.5)
    os.system("pip3 install cryptography")
    time.sleep(0.5)
    os.system("pip3 install python-docx")
    time.sleep(0.5)
    os.system("pip3 install fpdf")
    time.sleep(0.5)
    os.system("pip3 install xlwt")
    time.sleep(0.5)
    os.system("pip3 install db-sqlite3")
    time.sleep(0.5)
    os.system("pip3 install flask")
    time.sleep(0.5)
    os.system("pip3 install flask_restful")
    time.sleep(0.5)
    os.system("pip3 install paramiko")
    time.sleep(0.5)
    os.system("pip3 install boto")
    time.sleep(0.5)
    os.system("pip3 install botocore")
    time.sleep(0.5)
    os.system("pip3 install coloredlogs")
    time.sleep(0.5)
    os.system("pip3 install verboselogs")
    time.sleep(0.5)
    os.system("pip3 install oauth2client==3.0.0")
    time.sleep(0.5)

input('\nPress enter to exit...')